services:
  txt_sink_mysql:
    image: mysql:latest
    container_name: txt_sink_mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: txt_sink
      MYSQL_PASSWORD: txt_sink
      MYSQL_DATABASE: txt_sink_db
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
