services:
  txt_sink_mysql:
    image: mysql:latest
    container_name: txt_sink_mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: txt_sink
      MYSQL_PASSWORD: txt_sink
      MYSQL_DATABASE: txt_sink_db
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
    driver: local
  minio-data:
    driver: local