""" AWS S3 settings """

AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_STORAGE_BUCKET_NAME = ""
AWS_S3_ENDPOINT_URL = "https://s3.amazonaws.com"
AWS_QUERYSTRING_AUTH = False
AWS_REGION = "us-east-1"

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
