name: CI Workflow

on: 
  push:
    branches:
      - dev
  workflow_call:


jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3.0.1
      with:
        poetry-version: 1.8.5

    - name: Setup a local virtual environment
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Activate the virtual environment
      run: source .venv/bin/activate

    - name: Install Dependencies
      run: poetry install --no-root

    - name: Lint Code
      run: make lint

    - name: Run Tests
      run: |
        source .venv/bin/activate
        export PYTHONPATH=$PYTHONPATH:/home/runner/work/txt-sink-api/txt-sink-api/src
        ls -alh &&  make test